import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
        
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen">
               <Navbar/>
               <main className="py-8">
                {/* container to center the screen */}
                    <div className="max-w-7xl mx-auto px-4">
                        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                              {/* this is the sidebar where we will have the profile and the things */}
                              {/* we dont need this in the bigger screens  */}
                              <div className="hidden lg:block lg:col-span-3">
                                  Sidebar
                              </div>
                              {/* this is the content main thing */}
                              <div className="lg:col-span-9">
                                  {children}
                              </div>
                        </div>
                    </div>
               </main>
            </div>
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
